image: node:10.15.0
options:
  max-time: 10
pipelines:
  branches:
    master:
      - step:
          name: Updating Docker Image
          services:
            - docker
          script:
            - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
            - docker build -t docker.io/israelpc15/milhas:producao .
            - docker push docker.io/israelpc15/milhas:producao
            # incluir comandos para fazer upload da imagem para docker hub